model_name: my_model_name
demo: false
pretrained: 2D_versatile_fluo
test_prop: 0.1
val_prop: 0.1
val_prop_opt: 1.0
epochs: 10
steps_per_epoch: 2
learning_rate: 0.0001
augment: true
random_seed: 42

early_stopping:
  monitor: val_prob_loss
  min_delta: 0.1
  patience: 5
  verbose: 0
  restore_best_weights: false
  start_from_epoch: 0
  mode: min

train_reduce_lr:
  factor: 0.5
  patience: 5
  min_delta: 0.0001

